// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_mN8p5ocwP7GQ_RI0XtxR9SNjtwKe9o',
    appId: '1:337188672655:web:e4993dac9c385597fd0cfa',
    messagingSenderId: '337188672655',
    projectId: 'meet-d9718',
    authDomain: 'meet-d9718.firebaseapp.com',
    storageBucket: 'meet-d9718.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2-y3R_MYZSyzgKsmBCc9Hu0KMQK-HObI',
    appId: '1:337188672655:android:ea043f9ae132768efd0cfa',
    messagingSenderId: '337188672655',
    projectId: 'meet-d9718',
    storageBucket: 'meet-d9718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZJZ948CEw0GNVzHwlbFNP2ionl1sDAo',
    appId: '1:337188672655:ios:3e78984c9ac5beb2fd0cfa',
    messagingSenderId: '337188672655',
    projectId: 'meet-d9718',
    storageBucket: 'meet-d9718.appspot.com',
    androidClientId: '337188672655-irs27b9otp3a45112if2fbth04oirsbf.apps.googleusercontent.com',
    iosClientId: '337188672655-8g3sg78jrq4s3fgudf50oee645k8ophk.apps.googleusercontent.com',
    iosBundleId: 'com.kapp.meetTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFZJZ948CEw0GNVzHwlbFNP2ionl1sDAo',
    appId: '1:337188672655:ios:3e78984c9ac5beb2fd0cfa',
    messagingSenderId: '337188672655',
    projectId: 'meet-d9718',
    storageBucket: 'meet-d9718.appspot.com',
    androidClientId: '337188672655-irs27b9otp3a45112if2fbth04oirsbf.apps.googleusercontent.com',
    iosClientId: '337188672655-8g3sg78jrq4s3fgudf50oee645k8ophk.apps.googleusercontent.com',
    iosBundleId: 'com.kapp.meetTogether',
  );
}
