// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_mN8p5ocwP7GQ_RI0XtxR9SNjtwKe9o',
    appId: '1:337188672655:web:db853223b23daa1cfd0cfa',
    messagingSenderId: '337188672655',
    projectId: 'meet-d9718',
    authDomain: 'meet-d9718.firebaseapp.com',
    storageBucket: 'meet-d9718.appspot.com',
    measurementId: 'G-P4D0GRHLZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2-y3R_MYZSyzgKsmBCc9Hu0KMQK-HObI',
    appId: '1:337188672655:android:6d9cc63a66f2b063fd0cfa',
    messagingSenderId: '337188672655',
    projectId: 'meet-d9718',
    storageBucket: 'meet-d9718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZJZ948CEw0GNVzHwlbFNP2ionl1sDAo',
    appId: '1:337188672655:ios:4952cbf4dd707d98fd0cfa',
    messagingSenderId: '337188672655',
    projectId: 'meet-d9718',
    storageBucket: 'meet-d9718.appspot.com',
    androidClientId: '337188672655-0pc9386lpadfc51hs4t5m5f1her31t03.apps.googleusercontent.com',
    iosClientId: '337188672655-8g3sg78jrq4s3fgudf50oee645k8ophk.apps.googleusercontent.com',
    iosBundleId: 'com.kapp.meetTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFZJZ948CEw0GNVzHwlbFNP2ionl1sDAo',
    appId: '1:337188672655:ios:4952cbf4dd707d98fd0cfa',
    messagingSenderId: '337188672655',
    projectId: 'meet-d9718',
    storageBucket: 'meet-d9718.appspot.com',
    androidClientId: '337188672655-0pc9386lpadfc51hs4t5m5f1her31t03.apps.googleusercontent.com',
    iosClientId: '337188672655-8g3sg78jrq4s3fgudf50oee645k8ophk.apps.googleusercontent.com',
    iosBundleId: 'com.kapp.meetTogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq_mN8p5ocwP7GQ_RI0XtxR9SNjtwKe9o',
    appId: '1:337188672655:web:08f04c4f2310011bfd0cfa',
    messagingSenderId: '337188672655',
    projectId: 'meet-d9718',
    authDomain: 'meet-d9718.firebaseapp.com',
    storageBucket: 'meet-d9718.appspot.com',
    measurementId: 'G-KFJ3N2ZCLG',
  );

}